using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

[System.Serializable]
public class LightEffectAreaInfos
{

    public float width = 0.1f;//0 -- 1
    public float duijiaoLen = 0.2f;
}
public class LightEffect : MonoBehaviour
{
    //暂时用C# 编写使用CPU 擅长shader的人自己改成GPU
    // Start is called before the first frame update
    public Color selectColor = Color.white;
    public float speed = 20;
    public float angle = 0;
    public Vector2 size = new Vector2(100,100);
    public List<LightEffectAreaInfos> lightEffectAreaInfos = new List<LightEffectAreaInfos>();
    private float time = 0;
    private Texture2D texture2D = null;
    private int width = 0;
    private int height = 0;
    void Start()
    {
        if(texture2D == null)initMember();
    }
    private void initMember()
    {
    }
    void updateTexture()
    {
    }
    // Update is called once per frame
    void Update()
    {
        if (texture2D == null) initMember();
    }
}
