using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HomeScript : MonoBehaviour
{
    public Image img_one,image_two,image_three;
    public Sprite[] clickImgs;
    public Sprite[] noclickImgs;
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void clickOne()
    {
        Debug.Log("点击one");
        //img_one.sprite
        img_one.sprite = clickImgs[0];
        image_two.sprite = noclickImgs[1];
        image_three.sprite = noclickImgs[2];
    }
    public void clickTwo()
    {
        Debug.Log("点击two");
        img_one.sprite = noclickImgs[0];
        image_two.sprite = clickImgs[1];
        image_three.sprite = noclickImgs[2];
    }
    public void clcikThree()
    {
        Debug.Log("点击three");
        img_one.sprite = noclickImgs[0];
        image_two.sprite = noclickImgs[1];
        image_three.sprite = clickImgs[2];

    }
}
